---
title: "simple Logistic Regression"
output:
  html_document:
    theme: cerulean
    toc: yes
    toc_depth: 3
    number_sections: false
    toc_float: 
       collapsed: true
    #code_folding: hide
---

```{=html}
<style>
h2 {
  background-color: #D4DAEC;
}
</style>
```

---
```{r setup,echo=FALSE}

knitr::opts_chunk$set(echo = FALSE,eval=FALSE)

```



## Exercise

Goal: association between survival (survived==1) and other factors including age, sex, and ticket fare.


```{r,message=FALSE,echo=TRUE}

#Get Titanic data
library(Hmisc)
getHdata(titanic3)
head(titanic3)

dataForAnalysis=titanic3

```


## Data overview

Show the distribution of age and ticket fare in survivors and non-survivors


```{r}

#tapply(dataForAnalysis$age,dataForAnalysis$survived,summary)

boxplot(dataForAnalysis$age~dataForAnalysis$survived)

boxplot(dataForAnalysis$fare~dataForAnalysis$survived)


```


## Perform multiple logistic regression analysis and show odds ratio of each factor

```{r}

modelResult <- glm(survived ~ age+fare+sex, data = dataForAnalysis,family = "binomial")
summary(modelResult)

#Odds ratio
exp(modelResult$coefficients)

```

### Model evaluation

Show the diagnostic plot of the model

```{r}

op=par(mfrow=c(2,2),mar=c(4,4,2,2))
plot(modelResult)

par(op)

```








