---
title: "simple Logistic Regression"
output:
  html_document:
    theme: cerulean
    toc: yes
    toc_depth: 3
    number_sections: false
    toc_float: 
       collapsed: true
    #code_folding: hide
---

```{=html}
<style>
h2 {
  background-color: #D4DAEC;
}
</style>
```




## Exercise

Goal: Goal: association between survival (survived==1) and age (age).


```{r,message=FALSE}

#Get Titanic data
library(Hmisc)
getHdata(titanic3)
head(titanic3)

dataForAnalysis=titanic3

```


## Data overview

Percent of survivors
Distribution of age
Distribution of age in survivors and non-survivors

```{r}

table(dataForAnalysis$survived)
tapply(dataForAnalysis$age,dataForAnalysis$survived,summary)

boxplot(dataForAnalysis$age~dataForAnalysis$survived)

```


## Perform logistic regression analysis

```{r}

modelResult <- glm(survived ~ age, data = dataForAnalysis,family = "binomial")
summary(modelResult)

#Odds ratio
exp(modelResult$coefficients)

```

### Model evaluation


```{r}

op=par(mfrow=c(2,2),mar=c(4,4,2,2))
plot(modelResult)

par(op)

```




```{r}

library(effects)
allEffects(modelResult)
plot(allEffects(modelResult))


```






