---
title: "simple Logistic Regression"
output:
  html_document:
    theme: cerulean
    toc: yes
    toc_depth: 3
    number_sections: false
    toc_float: 
       collapsed: true
    #code_folding: hide
---

```{=html}
<style>
h2 {
  background-color: #D4DAEC;
}
</style>
```

## Introduction of the methods (recapture the course)


-   Motivation
-   Data overview
-   Perform logistic regression analysis
-   Model evaluation



Short introduction about data and Motivations here.

Goal: association between transmission type (0=automatic; 1=manual) and weight of cars.

```{r}

dataForAnalysis=mtcars

```

## Data overview


```{r}

table(dataForAnalysis$am)
tapply(dataForAnalysis$wt,dataForAnalysis$am,summary)

boxplot(dataForAnalysis$wt~dataForAnalysis$am)

```


## Perform logistic regression analysis

```{r}

modelResult <- glm(am ~ wt, data = dataForAnalysis,family = "binomial")
summary(modelResult)

#Odds ratio
exp(modelResult$coefficients)

```

### Model evaluation


```{r}

op=par(mfrow=c(2,2),mar=c(4,4,2,2))
plot(modelResult)

par(op)

```




```{r}

library(effects)
allEffects(modelResult)
plot(allEffects(modelResult),axes=list(x=list(rug=FALSE)))


```




### Predict new data

```{r}

newData <- data.frame(wt = c(NewCar1=2.3,NewCar2=4.7))
result <-  predict.glm(modelResult,newData,type ="response") #probabilities
print(result)


```




